# Generated by Django 6.0.3 on 2026-03-20 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('writer', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(default=0)),
                ('english', models.TextField()),
                ('urdu', models.TextField(blank=True, null=True)),
                ('arabic', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='hadith.book')),
            ],
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadith_number', models.IntegerField(default=0)),
                ('english_number', models.IntegerField(blank=True, null=True)),
                ('narrator', models.CharField(blank=True, max_length=255, null=True)),
                ('text_urdu', models.TextField()),
                ('text_arabic', models.TextField(blank=True, null=True)),
                ('text_english', models.TextField(blank=True, null=True)),
                ('heading_arabic', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiths', to='hadith.book')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiths', to='hadith.chapter')),
            ],
        ),
    ]
